/**
 * this class created for viewing the map of the game and generating the whole map view
 *
 * @author Mohammadreza Hassanzadeh
 * @since 18 Nov 2020
 * @version 1.0
 */
public class View {
    /**
     * this method will view the map of the game
     */
    public static void viewingTheMap(){
        String[][] elementLocations = GameManager.getGameLocations();
        String[][] mapTypesLocations = GameManager.getLocationTypes();
        System.out.println(Colors.RED_BOLD + "       0*              1*              2*              3*              4*              5*              6*              7*              8*              9*              10              11              12       \n" + Colors.RESET);
        for(int i = 0; i < 10; i += 2 ){
            if(i == 8){
                System.out.print("       **              **              **              **              **              **              **              **              **              **              **              **              **       \n" +
                                 "   *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *    \n" +
                                 "*      "+(mapTypesLocations[i][0])+"      **     "+(mapTypesLocations[i][1])+"       **     "+(mapTypesLocations[i][2])+"       **     "+(mapTypesLocations[i][3])+"       **     "+(mapTypesLocations[i][4] )+"       **     "+(mapTypesLocations[i][5])+"       **     "+(mapTypesLocations[i][6])+"       **     "+(mapTypesLocations[i][7])+"       **     "+(mapTypesLocations[i][8])+"       **     "+(mapTypesLocations[i][9])+"       **     "+(mapTypesLocations[i][10])+"       **     "+(mapTypesLocations[i][11] )+"       **     "+(mapTypesLocations[i][12] )+"       *\n" +
                                 Colors.RED_BOLD + i  + Colors.RESET+ "    " + ((elementLocations[i][0] != null) ? elementLocations[i][0] : "      ")+"    **    " + ((elementLocations[i][1] != null) ? elementLocations[i][1] : "      ")+"    **    " + ((elementLocations[i][2] != null) ? elementLocations[i][2] : "      ")+"    **    " + ((elementLocations[i][3] != null) ? elementLocations[i][3] : "      ")+"    **    " + ((elementLocations[i][4] != null) ? elementLocations[i][4] : "      ")+"    **    " + ((elementLocations[i][5] != null) ? elementLocations[i][5] : "      ")+"    **    " + ((elementLocations[i][6] != null) ? elementLocations[i][6] : "      ")+"    **    " + ((elementLocations[i][7] != null) ? elementLocations[i][7] : "      ")+"    **    " + ((elementLocations[i][8] != null) ? elementLocations[i][8] : "      ")+"    **    " + ((elementLocations[i][9] != null) ? elementLocations[i][9] : "      ")+"    **    " + ((elementLocations[i][10] != null) ? elementLocations[i][10] : "      ")+"    **    " + ((elementLocations[i][11] != null) ? elementLocations[i][11] : "      ")+"    **    " + ((elementLocations[i][12] != null) ? elementLocations[i][12] : "      ")+"    " + Colors.RED_BOLD + i  + Colors.RESET + "\n" +
                                 "*              **              **              **              **              **              **              **              **              **              **              **              **              *\n" +
                                 "   *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *   \n" +
                                 "       **              **              **              **              **              **              **              **              **              **              **              **              **        \n");
                break;
            }
            System.out.print("       **              **              **              **              **              **              **              **              **              **              **              **              **       \n" +
                             "   *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *    \n" +
                             "*      "+(mapTypesLocations[i][0])+"      **     "+(mapTypesLocations[i][1])+"       **     "+(mapTypesLocations[i][2])+"       **     "+(mapTypesLocations[i][3])+"       **     "+(mapTypesLocations[i][4] )+"       **     "+(mapTypesLocations[i][5])+"       **     "+(mapTypesLocations[i][6])+"       **     "+(mapTypesLocations[i][7])+"       **     "+(mapTypesLocations[i][8])+"       **     "+(mapTypesLocations[i][9])+"       **     "+(mapTypesLocations[i][10])+"       **     "+(mapTypesLocations[i][11] )+"       **     "+(mapTypesLocations[i][12] )+"       *\n" +
                             Colors.RED_BOLD + i  + Colors.RESET+ "    " + ((elementLocations[i][0] != null) ? elementLocations[i][0] : "      ")+"    **    " + ((elementLocations[i][1] != null) ? elementLocations[i][1] : "      ")+"    **    " + ((elementLocations[i][2] != null) ? elementLocations[i][2] : "      ")+"    **    " + ((elementLocations[i][3] != null) ? elementLocations[i][3] : "      ")+"    **    " + ((elementLocations[i][4] != null) ? elementLocations[i][4] : "      ")+"    **    " + ((elementLocations[i][5] != null) ? elementLocations[i][5] : "      ")+"    **    " + ((elementLocations[i][6] != null) ? elementLocations[i][6] : "      ")+"    **    " + ((elementLocations[i][7] != null) ? elementLocations[i][7] : "      ")+"    **    " + ((elementLocations[i][8] != null) ? elementLocations[i][8] : "      ")+"    **    " + ((elementLocations[i][9] != null) ? elementLocations[i][9] : "      ")+"    **    " + ((elementLocations[i][10] != null) ? elementLocations[i][10] : "      ")+"    **    " + ((elementLocations[i][11] != null) ? elementLocations[i][11] : "      ")+"    **    " + ((elementLocations[i][12] != null) ? elementLocations[i][12] : "      ")+"    " + Colors.RED_BOLD + i  + Colors.RESET + "\n" +
                             "*              **              **              **              **              **              **              **              **              **              **              **              **              *\n" +
                             "   *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *      *        *   \n" +
                             "       **     "+(mapTypesLocations[i + 1][0])+"       **     "+(mapTypesLocations[i + 1][1])+"       **     "+(mapTypesLocations[i + 1][2] )+"       **     "+(mapTypesLocations[i + 1][3])+"       **     "+(mapTypesLocations[i + 1][4])+"       **     "+(mapTypesLocations[i + 1][5] )+"       **     "+(mapTypesLocations[i + 1][6] )+"       **     "+(mapTypesLocations[i + 1][7])+"       **     "+(mapTypesLocations[i + 1][8] )+"       **     "+(mapTypesLocations[i + 1][9] )+"       **     "+(mapTypesLocations[i + 1][10])+"       **     "+(mapTypesLocations[i + 1][11])+"       *\n" +
                             "       *" + Colors.RED_BOLD + (i + 1)  + Colors.RESET+ "    " + ((elementLocations[i + 1][0] != null) ? elementLocations[i + 1][0] : "      ")+"    **    " + ((elementLocations[i + 1][1] != null) ? elementLocations[i + 1][1] : "      ")+"    **    " + ((elementLocations[i + 1][2] != null) ? elementLocations[i + 1][2] : "      ")+"    **    " + ((elementLocations[i + 1][3] != null) ? elementLocations[i + 1][3] : "      ")+"    **    " + ((elementLocations[i + 1][4] != null) ? elementLocations[i + 1][4] : "      ")+"    **    " + ((elementLocations[i + 1][5] != null) ? elementLocations[i + 1][5] : "      ")+"    **    " + ((elementLocations[i + 1][6] != null) ? elementLocations[i + 1][6] : "      ")+"    **    "+ ((elementLocations[i + 1][7] != null) ? elementLocations[i + 1][7] : "      ")+"    **    "+ ((elementLocations[i + 1][8] != null) ? elementLocations[i + 1][8] : "      ")+"    **    "+ ((elementLocations[i + 1][9] != null) ? elementLocations[i + 1][9] : "      ")+"    **    "+ ((elementLocations[i + 1][10] != null) ? elementLocations[i + 1][10] : "      ")+"    **    "+ ((elementLocations[i + 1][11] != null) ? elementLocations[i + 1][11] : "      ")+"    *" + Colors.RED_BOLD + (i + 1)  + Colors.RESET+ "         \n");
        }
        System.out.println(Colors.RED_BOLD + "       0*              1*              2*              3*              4*              5*              6*              7*              8*              9*              10              11              12       \n" + Colors.RESET);
    }
}
